/**
 */
package tiendacristal.ui.contenedorcrudpedido.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import tiendacristal.ui.contenedorcrudpedido.util.ContenedorcrudpedidoAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ContenedorcrudpedidoItemProviderAdapterFactory extends ContenedorcrudpedidoAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ContenedorcrudpedidoItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link tiendacristal.ui.contenedorcrudpedido.ContenedorCRUDPedidoViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorCRUDPedidoViewModelItemProvider contenedorCRUDPedidoViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link tiendacristal.ui.contenedorcrudpedido.ContenedorCRUDPedidoViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorCRUDPedidoViewModelAdapter() {
		if (contenedorCRUDPedidoViewModelItemProvider == null) {
			contenedorCRUDPedidoViewModelItemProvider = new ContenedorCRUDPedidoViewModelItemProvider(this);
		}

		return contenedorCRUDPedidoViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link tiendacristal.ui.contenedorcrudpedido.ContenedorDetallePedidoViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorDetallePedidoViewModelItemProvider contenedorDetallePedidoViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link tiendacristal.ui.contenedorcrudpedido.ContenedorDetallePedidoViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorDetallePedidoViewModelAdapter() {
		if (contenedorDetallePedidoViewModelItemProvider == null) {
			contenedorDetallePedidoViewModelItemProvider = new ContenedorDetallePedidoViewModelItemProvider(this);
		}

		return contenedorDetallePedidoViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link tiendacristal.ui.contenedorcrudpedido.ContenedorMaestroPedidoViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorMaestroPedidoViewModelItemProvider contenedorMaestroPedidoViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link tiendacristal.ui.contenedorcrudpedido.ContenedorMaestroPedidoViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorMaestroPedidoViewModelAdapter() {
		if (contenedorMaestroPedidoViewModelItemProvider == null) {
			contenedorMaestroPedidoViewModelItemProvider = new ContenedorMaestroPedidoViewModelItemProvider(this);
		}

		return contenedorMaestroPedidoViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link tiendacristal.ui.contenedorcrudpedido.ProductoComprarViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductoComprarViewModelItemProvider productoComprarViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link tiendacristal.ui.contenedorcrudpedido.ProductoComprarViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductoComprarViewModelAdapter() {
		if (productoComprarViewModelItemProvider == null) {
			productoComprarViewModelItemProvider = new ProductoComprarViewModelItemProvider(this);
		}

		return productoComprarViewModelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (contenedorCRUDPedidoViewModelItemProvider != null) contenedorCRUDPedidoViewModelItemProvider.dispose();
		if (contenedorDetallePedidoViewModelItemProvider != null) contenedorDetallePedidoViewModelItemProvider.dispose();
		if (contenedorMaestroPedidoViewModelItemProvider != null) contenedorMaestroPedidoViewModelItemProvider.dispose();
		if (productoComprarViewModelItemProvider != null) productoComprarViewModelItemProvider.dispose();
	}

}
